services:
  redis_ynPf:
    image: redis:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - ${HOST_IP}:${REDIS_PORT}:6379
    volumes:
      - ${APP_PATH}/data:/data
      - ${APP_PATH}/logs:/logs
      - ${APP_PATH}/redis.conf:/etc/redis/redis.conf
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true